language: node_js
node_js:
- '10'
- '8'
- '6'
after_success: npm run before_dist && npm run dist
before_deploy:
- cd dist
deploy:
  provider: npm
  email: daveamit@live.com
  api_key:
    secure: qDaj41uLeXQhboN6CeYZMskxGIep0gn9OwZp7FrxL/+rNWXRVzlWqRQEDfkOOwMQ1ReiATEYrS/yZZYkcD9X5D/Y7+hypLPgtLxkC2r90aoSk1qfKzwBcyLQryBtPgBB47S/bXnbXTj7R+qq34mDKDYmSSObRyvimyZTABvTqTVQ7nYqlc55+/qEvesI7t/9m4DPFFp4G1HBBoXPJoze9IGvrn2Ub84BZLmbwpc06m4Nf6Y9yVMsYRk+O99QUGAHxl4kZN1O7Hym9YbdI2rDkv2bQZGO1hRn8oryJxfaLQX6gcZ5HJ+kuXjoQS/2l3oiX5TYpirhotHKS2MgM6NCU02TNFkhwokQMoCIsH0K/UdYu59LManaUwWiwB8DEL8bneXTSJB2ZCH1xEXu2oupVEs3flHmDjWF0IbM/dUOhw/OnJGO1Z2mg9swu6yIwktHFTjGqW0yjqfE0qODr+wA3LuJnxl7YV38K4mY7ESovl5NWqJ3EKJgIgHhp0NsiVmZd3mURCGZyPqSLx1SPuGnm2bnuevm6Mr4RwpKUHsnO357x05pz6MINHpZ0ENkJhw4cwnFQJhO/1MopgAg42oWzeZ2eoHpWxGC3QeUNKy1ktfJLF6sSsGHgpyMmZ1utoRPxwPm/q3R89HrvCTvw/4d44IiaxzUJUjmKUtYtSyJRtI=
  on:
    tags: true
    repo: daveamit/autonomous
